CC=g++


compile:
	$(CC) -o main main.cpp grid.cpp point.cpp math_functions.cpp input_functions.cpp -std=gnu++11

run:
	$(CC) -o main main.cpp grid.cpp point.cpp math_functions.cpp input_functions.cpp -std=gnu++11
	./main
